import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { build } from 'esbuild';

const execFileAsync = promisify(execFile);
const rootDir = resolve(import.meta.dirname, '..');
const distDir = resolve(rootDir, 'dist-print-agent');
const packageDir = resolve(rootDir, 'dist-print-agent', 'YANLCPrintAgent');
const buildDir = resolve(distDir, '.build');
const zipPath = resolve(distDir, 'YANLCPrintAgent.zip');
const bundlePath = resolve(buildDir, 'YANLCPrintAgent.mjs');
const exePath = resolve(packageDir, 'YANLCPrintAgent.exe');
const entryFile = resolve(rootDir, 'print-agent', 'src', 'index.ts');

async function main() {
  await rm(distDir, { recursive: true, force: true });
  await mkdir(buildDir, { recursive: true });
  await mkdir(resolve(packageDir, 'logs'), { recursive: true });

  await build({
    entryPoints: [entryFile],
    outfile: bundlePath,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node24',
    sourcemap: false,
    minify: false,
    banner: {
      js: '// YANLC Print Agent portable bundle. Generated by scripts/build-print-agent-package.ts',
    },
  });

  await buildExe();
  await writeText('config.example.json', `${JSON.stringify({
    supabaseUrl: 'https://your-project.supabase.co',
    supabaseKey: 'your-supabase-publishable-key',
    adminEmail: 'admin@example.com',
    adminPassword: 'change-me',
    printerName: '',
    paperWidth: '80',
    pollIntervalMs: 3000,
    autoPrint: true,
    maxOrdersPerPoll: 10,
  }, null, 2)}\n`);

  await writeText('setup.cmd', commandFile([
    'title YANLC Print Agent Setup',
    'echo.',
    'echo YANLC Print Agent - Setup',
    'echo =========================',
    'echo.',
    'YANLCPrintAgent.exe --setup',
    'echo.',
    'pause',
  ]));

  await writeText('start.cmd', commandFile([
    'title YANLC Print Agent',
    'echo.',
    'echo YANLC Print Agent',
    'echo =================',
    'echo Keep this window open. Closing it will stop automatic printing.',
    'echo.',
    'YANLCPrintAgent.exe',
    'echo.',
    'echo Print agent exited. Press any key to close this window.',
    'pause >nul',
  ]));

  await writeText('test-print.cmd', commandFile([
    'title YANLC Test Print',
    'echo.',
    'echo This will send one sample kitchen ticket to the configured printer.',
    'echo.',
    'choice /C YN /M "Run test print"',
    'if errorlevel 2 goto end',
    'YANLCPrintAgent.exe --test-print',
    ':end',
    'echo.',
    'pause',
  ]));

  await writeText('list-printers.cmd', commandFile([
    'title YANLC Printer List',
    'echo.',
    'echo Reading Windows printer list...',
    'echo.',
    'YANLCPrintAgent.exe --list-printers',
    'echo.',
    'pause',
  ]));

  await writeText('install-startup.cmd', commandFile([
    'title YANLC Install Startup',
    'echo.',
    'echo Installing Windows startup shortcut...',
    'echo.',
    'YANLCPrintAgent.exe --install-startup',
    'echo.',
    'pause',
  ]));

  await writeText('uninstall-startup.cmd', commandFile([
    'title YANLC Uninstall Startup',
    'set "SHORTCUT=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\YANLC Print Agent.lnk"',
    'echo.',
    'echo Removing Windows startup shortcut...',
    'if exist "%SHORTCUT%" (',
    '  del "%SHORTCUT%"',
    '  echo Startup shortcut removed:',
    '  echo %SHORTCUT%',
    ') else (',
    '  echo Startup shortcut was not found.',
    ')',
    'echo.',
    'pause',
  ]));

  await writeText('README.txt', readmeText());
  await createZip();
  await writeChecksum();
  console.log(`Portable print agent package generated: ${packageDir}`);
  console.log(`Portable zip generated: ${zipPath}`);
}

function commandFile(lines: string[]) {
  return `@echo off\r\nsetlocal\r\ncd /d "%~dp0"\r\n${lines.join('\r\n')}\r\n`;
}

async function writeText(name: string, content: string) {
  await writeFile(resolve(packageDir, name), content, 'utf8');
}

async function buildExe() {
  await execFileAsync('cmd.exe', [
    '/c',
    'pnpm',
    'exec',
    'pkg',
    bundlePath,
    '--targets',
    'node24-win-x64',
    '--output',
    exePath,
    '--compress',
    'GZip',
  ], {
    cwd: rootDir,
    windowsHide: true,
    timeout: 120000,
  });
}

function readmeText() {
  return `YANLC Print Agent portable package
==================================

This folder is the portable Windows print agent for restaurant kitchen tickets.

Customer computer requirements:
- Windows 10 or Windows 11
- A Windows-installed printer that can print the Windows test page
- Internet access

First-time setup:
1. Copy the whole YANLCPrintAgent folder to the customer computer.
2. Install the printer driver in Windows.
3. Confirm the Windows test page prints correctly.
4. Double-click setup.cmd and fill in:
   - Supabase URL
   - Supabase publishable key
   - Admin email
   - Admin password
   - Printer name, or leave empty for Windows default printer
   - Paper width, 58 or 80
   - Auto print, true or false
5. Double-click test-print.cmd to print a sample ticket.
6. Double-click start.cmd to start automatic printing.
7. Optional: double-click install-startup.cmd to start automatically when Windows starts.

Important:
- Keep the start.cmd window open. Closing it stops automatic printing.
- config.json is created locally by setup.cmd. Do not share it publicly.
- logs are saved in the logs folder.
- Kitchen tickets are not Greek fiscal receipts.
- Official tax receipts must still be issued by the restaurant's legal cash register or POS.

Files:
- YANLCPrintAgent.exe: application entry
- setup.cmd: interactive setup
- start.cmd: start automatic printing
- test-print.cmd: sample print
- list-printers.cmd: show Windows printers
- install-startup.cmd: install Windows startup shortcut
- uninstall-startup.cmd: remove Windows startup shortcut
- config.example.json: example only, not real credentials
- logs/: runtime logs
`;
}

async function createZip() {
  const command = [
    `Compress-Archive -Path '${escapePowerShell(packageDir)}'`,
    `-DestinationPath '${escapePowerShell(zipPath)}'`,
    '-Force',
  ].join(' ');

  await execFileAsync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', command], {
    windowsHide: true,
    timeout: 30000,
  });
}

async function writeChecksum() {
  const content = await readFile(zipPath);
  const sha256 = createHash('sha256').update(content).digest('hex');
  const checksumPath = `${zipPath}.sha256.txt`;
  await writeFile(checksumPath, `${sha256}  YANLCPrintAgent.zip\n`, 'utf8');
}

function escapePowerShell(value: string) {
  return value.replace(/'/g, "''");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
